#!/usr/bin/perl

use strict;
use warnings;
use diagnostics;

sub parse_params {
    my %map;
    if ($#ARGV !=1 && $#ARGV !=3) {
        return %map;
    } elsif ($ARGV[0] ne '-h') {
        if ($ARGV[0] ne '-m' || $ARGV[2] ne '-h') {
            return  %map;
        }
    } elsif ($#ARGV == 3 && $ARGV[2] ne '-h' && $ARGV[2] ne '-m') {
        return %map;
    }

    $map{$ARGV[0]} = $ARGV[1];
    if ($#ARGV == 3) {
        $map{$ARGV[2]} = $ARGV[3];
    }
    return %map;
}

my %params = parse_params();
unless (%params) {
    print "正确的命令行格式为：./install -h MONITOR_HOST [-m MULTICAST_ADDR]\n\n";

    print "-h MONITOR_HOST\t\t\t";
    print "这是必选的参数，MONITOR_HOST表示监控服务器地址，可以是具体的IP地址（如192.168.8.42）,也可以是主机名（如node1）\n";
    print "-m MULTICAST_ADDR\t\t";
    print "这是可选的参数，MULTICAST_ADDR表示gmond的多播地址\n";
    exit 1;
}

do 'functions.pl';
install_package('libganglia-3.6.0');
install_package('ganglia-gmond-3.6.0');
install_package('ganglia-gmond-modules-python-3.6.0');
install_package('gpfsmond-2.0');

my $gpfsmond_script_file = '/usr/local/gpfsmonitor/gpfsmond/sbin/gpfsmond';
my $gpfsmond_script_content = read_file($gpfsmond_script_file);
$gpfsmond_script_content =~ s/localhost/$params{'-h'}/;
write_file($gpfsmond_script_file, $gpfsmond_script_content);

`service gmond start`;
