#!/usr/bin/perl

use strict;
do 'functions.pl';

remove_package('gpfsmond-2.0');
remove_package('ganglia-gmond-modules-python-3.6.0');
remove_package('ganglia-gmond-3.6.0');
if (get_full_package_name('ganglia-gmetad-3.6.0')) {
    print "libganglia-3.6.0 is needed by ganglia-gmetad-3.6.0, nothing to do\n";
} else {
    remove_package('libganglia-3.6.0');
}
