#!/usr/bin/python

from socket import *
import time

HOST = '192.168.8.43'
PORT = 9649
BUFSIZE = 1024
ADDR = (HOST, PORT)

cliSock = socket(AF_INET, SOCK_DGRAM)
while True:
    clusterName = 'v_cluster'
    for i in range(1, 3):
        hostName = 'vHost' + ('%i'%i)
        domainName = 'vNode' + ('%i'%i)
        for j in range(9, 14):
            fsName = 'gpfs' + ('%i'%j)
            mountedPath = '/gpfs_home' + ('%i'%j)

            data = "ident:2:" + hostName
            data += ":20140117:" + clusterName
            data += "." + domainName
            data += ":3.4.0.27\n"
            data += "state:active:1\n"
            data += "verbs:::\n"
            data += "fs:" + fsName + ":" + mountedPath + ":mounted:ok::\n"
            timestamp = '%i'%(time.time())
            data += "end:" + timestamp + ":" + timestamp +"\n"

            cliSock.sendto(data, ADDR)
            print 'send to ', HOST

    time.sleep(10)

cliSock.close()
